apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-login
  template:
    metadata:
      labels:
        app: arcadia-login
    spec:
      containers:
        - name: arcadia-login
          image: sorinboia/arcadia-login:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-login
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-login
